In [1]:
import numpy as np
#from numpy import array
#from numpy import arange

In [4]:
a = np.array([1,2,5,3,6,6,7])
a

array([1, 2, 5, 3, 6, 6, 7])

In [5]:
type(a)

numpy.ndarray

In [6]:
a.shape

(7,)

In [7]:
a = np.array([[1,2,5,4,7,8], [5,4,8,9,6,3]])
a

array([[1, 2, 5, 4, 7, 8],
       [5, 4, 8, 9, 6, 3]])

In [8]:
a.shape

(2, 6)

In [9]:
a = np.array([[[1,2,5,4,7,8], [5,4,8,9,6,3]],
              [[1,2,5,4,7,8], [5,4,8,9,6,3]],
              [[1,2,5,4,7,8], [5,4,8,9,6,3]],
              [[1,2,5,4,7,8], [5,4,8,9,6,3]]])
a

array([[[1, 2, 5, 4, 7, 8],
        [5, 4, 8, 9, 6, 3]],

       [[1, 2, 5, 4, 7, 8],
        [5, 4, 8, 9, 6, 3]],

       [[1, 2, 5, 4, 7, 8],
        [5, 4, 8, 9, 6, 3]],

       [[1, 2, 5, 4, 7, 8],
        [5, 4, 8, 9, 6, 3]]])

In [10]:
a.shape

(4, 2, 6)

In [12]:
a = np.array([[[[14,2,15,4,7], [5,24,8,9,6]],
              [[1,2,5,4,7], [5,4,8,19,6]],
              [[12,22,5,44,7], [5,24,8,91,6]],
              [[41,2,51,4,7], [5,4,8,9,6]]],
           [[[14,2,15,4,7], [5,24,8,9,6]],
              [[1,2,5,4,7], [5,4,8,19,6]],
              [[12,22,5,44,7], [5,24,8,91,6]],
              [[41,2,51,4,7], [5,4,8,9,6]]],
              [[[14,2,15,4,7], [5,24,8,9,6]],
              [[1,2,5,4,7], [5,4,8,19,6]],
              [[12,22,5,44,7], [5,24,8,91,6]],
              [[41,2,51,4,7], [5,4,8,9,6]]]])
a

array([[[[14,  2, 15,  4,  7],
         [ 5, 24,  8,  9,  6]],

        [[ 1,  2,  5,  4,  7],
         [ 5,  4,  8, 19,  6]],

        [[12, 22,  5, 44,  7],
         [ 5, 24,  8, 91,  6]],

        [[41,  2, 51,  4,  7],
         [ 5,  4,  8,  9,  6]]],


       [[[14,  2, 15,  4,  7],
         [ 5, 24,  8,  9,  6]],

        [[ 1,  2,  5,  4,  7],
         [ 5,  4,  8, 19,  6]],

        [[12, 22,  5, 44,  7],
         [ 5, 24,  8, 91,  6]],

        [[41,  2, 51,  4,  7],
         [ 5,  4,  8,  9,  6]]],


       [[[14,  2, 15,  4,  7],
         [ 5, 24,  8,  9,  6]],

        [[ 1,  2,  5,  4,  7],
         [ 5,  4,  8, 19,  6]],

        [[12, 22,  5, 44,  7],
         [ 5, 24,  8, 91,  6]],

        [[41,  2, 51,  4,  7],
         [ 5,  4,  8,  9,  6]]]])

In [13]:
#3 times an array structure having 4 arrays that contain 2 rows & 5 columns
a.shape

(3, 4, 2, 5)

In [14]:
a = np.arange(50)
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49])

In [15]:
a = np.arange(5, 50)
a

array([ 5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21,
       22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38,
       39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49])

In [16]:
a = np.arange(5, 50, 3)
a

array([ 5,  8, 11, 14, 17, 20, 23, 26, 29, 32, 35, 38, 41, 44, 47])

In [18]:
a = np.arange(24).reshape((6,4))
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [19]:
a = np.arange(26).reshape((6,4))
a

ValueError: cannot reshape array of size 26 into shape (6,4)

In [20]:
x = np.random.randint(1,10, 25)
x

array([8, 6, 1, 9, 4, 2, 5, 5, 6, 1, 1, 7, 1, 9, 5, 6, 3, 7, 2, 9, 4, 9,
       5, 3, 8])

In [21]:
x = np.random.randn()
x

1.0455465492532146

In [24]:
x = np.random.randn(5)
x

array([ 1.28062703, -0.78731289,  0.75355431,  0.43572424,  2.40525906])

In [25]:
x = np.random.random(10)
x

array([0.36800062, 0.33772144, 0.28050291, 0.85092514, 0.48225045,
       0.52672566, 0.55783935, 0.11442001, 0.51368579, 0.57111594])

In [28]:
x= np.random.choice(100,50,replace=False)
x

array([57, 55, 59, 88, 86, 43, 60, 32, 50,  3, 87, 62, 34, 85, 14, 68,  8,
       36,  9, 27, 99, 97, 95, 49, 39, 63, 70, 46, 96, 25,  1, 83, 78, 81,
       84, 79, 54, 37, 71, 41, 40, 74, 75, 17, 45, 90, 58, 31, 73, 30])

In [38]:
x = np.linspace(2,9,7)
x

array([2.        , 3.16666667, 4.33333333, 5.5       , 6.66666667,
       7.83333333, 9.        ])

In [41]:
for i in range(len(x)-1):
  print(i)
  print('Difference between index',i+1,'&',i,'is',x[i+1] - x[i])
x[2] - x[1]

0

Difference between index 1 & 0 is 1.166666666666667

1

Difference between index 2 & 1 is 1.166666666666667

2

Difference between index 3 & 2 is 1.166666666666666

3

Difference between index 4 & 3 is 1.166666666666667

4

Difference between index 5 & 4 is 1.166666666666667

5

Difference between index 6 & 5 is 1.166666666666666


1.166666666666667

In [36]:
x = np.linspace(3,9,9)
x

array([3.  , 3.75, 4.5 , 5.25, 6.  , 6.75, 7.5 , 8.25, 9.  ])

In [37]:
for i in range(len(x)-1):
  print(i)
  print('Difference between index',i+1,'&',i,'is',x[i+1] - x[i])

0

Difference between index 1 & 0 is 0.75

1

Difference between index 2 & 1 is 0.75

2

Difference between index 3 & 2 is 0.75

3

Difference between index 4 & 3 is 0.75

4

Difference between index 5 & 4 is 0.75

5

Difference between index 6 & 5 is 0.75

6

Difference between index 7 & 6 is 0.75

7

Difference between index 8 & 7 is 0.75


In [44]:
a = np.random.randint(0,9,21).reshape((3,7))
a

array([[3, 6, 8, 7, 8, 8, 0],
       [0, 5, 6, 1, 4, 7, 8],
       [8, 4, 8, 2, 6, 4, 6]])

In [51]:
#Columnwise summation
print(a)
a.sum(axis=0)

[[3 6 8 7 8 8 0]

 [0 5 6 1 4 7 8]

 [8 4 8 2 6 4 6]]


array([11, 15, 22, 10, 18, 19, 14])

In [52]:
#Columnwise summation
print(a)
a.sum(axis=1)

[[3 6 8 7 8 8 0]

 [0 5 6 1 4 7 8]

 [8 4 8 2 6 4 6]]


array([40, 31, 38])

In [53]:
print(a)
print(a.mean(axis=0))
print(a.mean(axis=1))

[[3 6 8 7 8 8 0]

 [0 5 6 1 4 7 8]

 [8 4 8 2 6 4 6]]

[3.66666667 5.         7.33333333 3.33333333 6.         6.33333333

 4.66666667]

[5.71428571 4.42857143 5.42857143]


In [54]:
print(a)
print(a.min(axis=0))
print(a.min(axis=1))

[[3 6 8 7 8 8 0]

 [0 5 6 1 4 7 8]

 [8 4 8 2 6 4 6]]

[0 4 6 1 4 4 0]

[0 0 2]


In [55]:
print(a)
print(a.max(axis=0))
print(a.max(axis=1))

[[3 6 8 7 8 8 0]

 [0 5 6 1 4 7 8]

 [8 4 8 2 6 4 6]]

[8 6 8 7 8 8 8]

[8 8 8]


In [62]:
#Cummulative Summation
a = np.random.randint(0,9,21)
print(a)
np.cumsum(a)

[1 4 3 8 1 6 1 3 5 3 8 6 3 4 2 1 1 7 3 7 5]


array([ 1,  5,  8, 16, 17, 23, 24, 27, 32, 35, 43, 49, 52, 56, 58, 59, 60,
       67, 70, 77, 82])

In [60]:
a = np.random.randint(0,9,28).reshape((4,7))
print(a)
np.square(a)

[[0 2 3 5 1 5 0]

 [7 0 0 7 7 2 5]

 [8 4 1 8 7 2 7]

 [3 7 7 1 2 6 6]]


array([[ 0,  4,  9, 25,  1, 25,  0],
       [49,  0,  0, 49, 49,  4, 25],
       [64, 16,  1, 64, 49,  4, 49],
       [ 9, 49, 49,  1,  4, 36, 36]])

In [64]:
a = np.random.randint(1,9,28).reshape((4,7))
print(a)
np.sqrt(a)

[[4 1 5 5 1 4 5]

 [5 8 3 6 2 6 6]

 [2 4 8 7 7 5 7]

 [7 5 1 2 4 3 3]]


array([[2.        , 1.        , 2.23606798, 2.23606798, 1.        ,
        2.        , 2.23606798],
       [2.23606798, 2.82842712, 1.73205081, 2.44948974, 1.41421356,
        2.44948974, 2.44948974],
       [1.41421356, 2.        , 2.82842712, 2.64575131, 2.64575131,
        2.23606798, 2.64575131],
       [2.64575131, 2.23606798, 1.        , 1.41421356, 2.        ,
        1.73205081, 1.73205081]])

In [65]:
#Horizontal Stack
a = np.random.randint(1,9,28).reshape((4,7))
print(a)
b = np.random.randint(1,9,20).reshape((4,5))
print(b)
np.hstack((a,b))

[[3 1 7 3 7 6 6]

 [4 6 8 2 7 3 4]

 [5 7 5 2 1 2 1]

 [2 4 1 3 8 3 1]]

[[1 7 4 6 5]

 [1 7 4 5 4]

 [1 7 4 5 4]

 [3 1 4 1 2]]


array([[3, 1, 7, 3, 7, 6, 6, 1, 7, 4, 6, 5],
       [4, 6, 8, 2, 7, 3, 4, 1, 7, 4, 5, 4],
       [5, 7, 5, 2, 1, 2, 1, 1, 7, 4, 5, 4],
       [2, 4, 1, 3, 8, 3, 1, 3, 1, 4, 1, 2]])

In [66]:
np.vstack((a,b))

ValueError: all the input array dimensions except for the concatenation axis must match exactly, but along dimension 1, the array at index 0 has size 7 and the array at index 1 has size 5

In [68]:
#Vertical Stack
a = np.random.randint(1,9,30).reshape((5,6))
print(a)
b = np.random.randint(1,9,24).reshape((4,6))
print(b)
np.vstack((a,b))

[[4 2 5 8 3 7]

 [6 3 1 3 6 1]

 [3 8 7 4 1 1]

 [2 6 3 5 2 3]

 [6 3 4 3 1 6]]

[[3 6 2 6 1 2]

 [3 4 4 5 3 3]

 [6 8 1 7 2 8]

 [5 3 2 6 6 5]]


array([[4, 2, 5, 8, 3, 7],
       [6, 3, 1, 3, 6, 1],
       [3, 8, 7, 4, 1, 1],
       [2, 6, 3, 5, 2, 3],
       [6, 3, 4, 3, 1, 6],
       [3, 6, 2, 6, 1, 2],
       [3, 4, 4, 5, 3, 3],
       [6, 8, 1, 7, 2, 8],
       [5, 3, 2, 6, 6, 5]])

In [3]:
Marks = np.random.randint(1,101,50)
Marks

array([82,  6, 19, 47, 26, 26, 27, 14, 61,  3, 86, 82, 69, 41, 72, 95, 70,
       87, 68, 11, 83, 66, 70, 55, 71, 54, 57, 71, 81, 65, 15, 30, 30, 66,
       76, 16, 79, 66, 40, 73, 23, 55,  2, 52, 72, 69, 93, 70, 43, 79])

In [4]:
for i in range(len(Marks)):
    if 75<=Marks[i] and  Marks[i]<=100:
        print(Marks[i],": Distinct")
    elif 60<=Marks[i] and  Marks[i]<=74:
        print(Marks[i],": First Division")
    elif 35<=Marks[i] and  Marks[i]<=59:
        print(Marks[i],": Second Division")
    else:
        print(Marks[i],": Fail")

82 : Distinct
6 : Fail
19 : Fail
47 : Second Division
26 : Fail
26 : Fail
27 : Fail
14 : Fail
61 : First Division
3 : Fail
86 : Distinct
82 : Distinct
69 : First Division
41 : Second Division
72 : First Division
95 : Distinct
70 : First Division
87 : Distinct
68 : First Division
11 : Fail
83 : Distinct
66 : First Division
70 : First Division
55 : Second Division
71 : First Division
54 : Second Division
57 : Second Division
71 : First Division
81 : Distinct
65 : First Division
15 : Fail
30 : Fail
30 : Fail
66 : First Division
76 : Distinct
16 : Fail
79 : Distinct
66 : First Division
40 : Second Division
73 : First Division
23 : Fail
55 : Second Division
2 : Fail
52 : Second Division
72 : First Division
69 : First Division
93 : Distinct
70 : First Division
43 : Second Division
79 : Distinct


In [5]:
Marks= np.random.choice(100,50,replace=False)
Marks

array([33, 20, 16, 23, 43, 62, 79,  1, 56, 55, 91, 22, 44, 39, 60, 13, 40,
       83, 98, 24, 99, 51,  9,  6, 15, 69, 28, 81, 45, 76, 25, 57,  2, 67,
       34, 94, 65, 74,  5, 96, 82, 63, 19, 85, 68, 66, 47, 27, 64, 93])

In [6]:
Dict = {}
for i in range(len(Marks)):
    if 75<=Marks[i] and  Marks[i]<=100:
        Dict[Marks[i]]="Distinct"
    elif 60<=Marks[i] and  Marks[i]<=74:
        Dict[Marks[i]]="First Division"
    elif 35<=Marks[i] and  Marks[i]<=59:
        Dict[Marks[i]]="Second Division"
    else:
        Dict[Marks[i]]="Fail"
        
Dict

{33: 'Fail',
 20: 'Fail',
 16: 'Fail',
 23: 'Fail',
 43: 'Second Division',
 62: 'First Division',
 79: 'Distinct',
 1: 'Fail',
 56: 'Second Division',
 55: 'Second Division',
 91: 'Distinct',
 22: 'Fail',
 44: 'Second Division',
 39: 'Second Division',
 60: 'First Division',
 13: 'Fail',
 40: 'Second Division',
 83: 'Distinct',
 98: 'Distinct',
 24: 'Fail',
 99: 'Distinct',
 51: 'Second Division',
 9: 'Fail',
 6: 'Fail',
 15: 'Fail',
 69: 'First Division',
 28: 'Fail',
 81: 'Distinct',
 45: 'Second Division',
 76: 'Distinct',
 25: 'Fail',
 57: 'Second Division',
 2: 'Fail',
 67: 'First Division',
 34: 'Fail',
 94: 'Distinct',
 65: 'First Division',
 74: 'First Division',
 5: 'Fail',
 96: 'Distinct',
 82: 'Distinct',
 63: 'First Division',
 19: 'Fail',
 85: 'Distinct',
 68: 'First Division',
 66: 'First Division',
 47: 'Second Division',
 27: 'Fail',
 64: 'First Division',
 93: 'Distinct'}

In [10]:
a = np.random.randint(1,9,12).reshape((3,4))
print(a)
print("\n")
b = np.random.randint(10,19,12).reshape((4,3))
print(b)

[[3 6 1 8]
 [3 2 7 6]
 [6 2 4 4]]


[[16 16 16]
 [11 11 17]
 [10 11 17]
 [10 12 18]]


In [12]:
c = a.T

In [14]:
x = np.dot(a,c)
x

array([[110,  76,  66],
       [ 76,  98,  74],
       [ 66,  74,  72]])

# ASSIGNMENT

**Create an identity matrix of dimension 4-by-4**

In [67]:
a = np.identity(4)
a

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

**Convert a 1-D array to a 3-D array**

In [18]:
b = np.random.choice(12,12).reshape((2,2,3))
b

array([[[ 3,  1,  6],
        [11,  3,  3]],

       [[ 5, 10, 11],
        [ 2,  0,  9]]])

**Convert all the elements of a numpy array from float to integer datatype**

In [5]:
c = np.array([3.7, -1.2, -2.6, 0.5, 12.9, 10.1])
c.astype(np.int64)

array([ 3, -1, -2,  0, 12, 10])

**Given a numpy array (matrix), how to get a numpy array output which is equal to the
original matrix multiplied by a scalar?**

In [59]:
d = np.arange(1,10).reshape(3,3)
d1 = np.identity(3)
print(d)
print("\n")
print(d1)
print("\n")
np.dot(d,d1)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]




array([[1., 2., 3.],
       [4., 5., 6.],
       [7., 8., 9.]])

**Given are 2 similar dimensional numpy arrays, how to get a numpy array output in
which every element is an element-wise sum of the 2 numpy arrays?**

In [14]:
e = np.random.randint(1,20,16).reshape(4,4)
e1 = np.random.randint(10,50,16).reshape(4,4)
print(e)
print("\n")
print(e1)
print("\n")
print(e+e1)

[[15 13 13 19]
 [17 11  4  8]
 [ 1 16  7 19]
 [17 17 17  3]]


[[18 39 31 32]
 [37 20 27 14]
 [26 47 45 44]
 [45 15 48 22]]


[[33 52 44 51]
 [54 31 31 22]
 [27 63 52 63]
 [62 32 65 25]]


**Convert a binary numpy array (containing only 0s and 1s) to a boolean numpy array**

In [60]:
f = np.random.choice(2,16,replace=True).reshape((4,4))
print(f)
print("\n")
print(f.astype(np.bool_))

[[0 1 0 0]
 [1 0 1 1]
 [1 1 0 1]
 [1 1 1 0]]


[[False  True False False]
 [ True False  True  True]
 [ True  True False  True]
 [ True  True  True False]]


**Stack 2 numpy arrays horizontally i.e., 2 arrays having the same 1st dimension (number
of rows in 2D arrays)**


In [24]:
g = np.random.randint(11,99,25).reshape((5,5))
print(g)
print("\n")
g1 = np.random.randint(10,90,20).reshape((5,4))
print(g1)
print("\n")
print(np.hstack((g,g1)))

[[28 62 65 22 23]
 [68 17 91 42 52]
 [93 33 25 11 38]
 [58 29 95 87 86]
 [29 45 38 27 36]]


[[55 78 29 31]
 [59 63 84 47]
 [67 45 42 58]
 [45 88 30 65]
 [84 55 44 13]]


[[28 62 65 22 23 55 78 29 31]
 [68 17 91 42 52 59 63 84 47]
 [93 33 25 11 38 67 45 42 58]
 [58 29 95 87 86 45 88 30 65]
 [29 45 38 27 36 84 55 44 13]]


**Stack 2 numpy arrays vertically i.e., 2 arrays having the same last dimension (number
of columns in 2D arrays)**

In [21]:
h = np.random.randint(11,99,25).reshape((5,5))
print(h)
print("\n")
h1 = np.random.randint(10,90,20).reshape((4,5))
print(h1)
print("\n")
print(np.vstack((h,h1)))

[[95 65 22 52 98]
 [11 36 21 30 21]
 [42 98 32 29 22]
 [81 94 35 39 87]
 [80 45 23 57 57]]


[[17 89 72 64 23]
 [89 27 72 35 80]
 [10 18 53 63 15]
 [61 63 71 17 15]]


[[95 65 22 52 98]
 [11 36 21 30 21]
 [42 98 32 29 22]
 [81 94 35 39 87]
 [80 45 23 57 57]
 [17 89 72 64 23]
 [89 27 72 35 80]
 [10 18 53 63 15]
 [61 63 71 17 15]]


**Generate a sequence of numbers in the form of a numpy array from 0 to 100 with gaps
of 2 numbers**

In [25]:
I = np.arange(0,101,2)
print(I)

[  0   2   4   6   8  10  12  14  16  18  20  22  24  26  28  30  32  34
  36  38  40  42  44  46  48  50  52  54  56  58  60  62  64  66  68  70
  72  74  76  78  80  82  84  86  88  90  92  94  96  98 100]


**From 2 numpy arrays, extract the indexes in which the elements in the 2 arrays match**

In [33]:
print(g)
print("\n")
print(h)
print("\n")
for i in range(len(g)):
    for j in range(i+1):
        if g[i][j]==h[i][j]:
            print(list[i,j])

[[28 62 65 22 23]
 [68 17 91 42 52]
 [93 33 25 11 38]
 [58 29 95 87 86]
 [29 45 38 27 36]]


[[95 65 22 52 98]
 [11 36 21 30 21]
 [42 98 32 29 22]
 [81 94 35 39 87]
 [80 45 23 57 57]]


list[4, 1]


**Output a sequence of equally gapped 5 numbers in the range 0 to 100 (both inclusive)**

In [34]:
J = np.arange(0,101,5)
J

array([  0,   5,  10,  15,  20,  25,  30,  35,  40,  45,  50,  55,  60,
        65,  70,  75,  80,  85,  90,  95, 100])

**Output a matrix (numpy array) of dimension 2-by-3 with each and every value equal to 5**

In [61]:
k = np.repeat(5,6).reshape((2,3))
k

array([[5, 5, 5],
       [5, 5, 5]])

**Output an array by repeating a smaller array of 2 dimensions, 10 times**

In [66]:
A = np.arange(1,5).reshape(2,2)
print(A)
print("\n")
A1 = np.repeat(A,10,axis=1)
print(A1)

[[1 2]
 [3 4]]


[[1 1 1 1 1 1 1 1 1 1 2 2 2 2 2 2 2 2 2 2]
 [3 3 3 3 3 3 3 3 3 3 4 4 4 4 4 4 4 4 4 4]]


**Output a 10-by-10 array of random integers between 0 (inclusive) and 10 (exclusive)**

In [38]:
m = np.random.randint(0,10,100).reshape(10,10)
print(m)

[[9 6 9 8 1 9 5 6 5 7]
 [8 1 5 5 2 7 3 9 8 6]
 [1 6 4 3 1 7 1 3 9 2]
 [9 0 8 7 2 1 9 3 0 4]
 [8 6 4 6 8 4 8 5 5 2]
 [3 6 5 1 9 9 6 9 2 7]
 [0 0 1 2 7 0 5 9 5 7]
 [4 3 8 4 0 9 2 5 1 7]
 [5 0 4 2 6 9 1 4 0 3]
 [5 6 0 3 0 0 2 9 1 3]]


**Given 2 numpy arrays as matrices, output the result of multiplying the 2 matrices (as a
numpy array)**

In [54]:
P*np.arange(16).reshape(4,4)
q = np.random.choice(50,16,replace=False).reshape((4,4))
print(P)
print("\n")
print(q)
print("\n")
print(P*q)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]


[[25 32 44 43]
 [42 23 19 35]
 [37 26 36  4]
 [31 49 24 20]]


[[  0  32  88 129]
 [168 115 114 245]
 [296 234 360  44]
 [372 637 336 300]]


**Output the transpose of a matrix (as numpy array)**

In [48]:
P = np.arange(16).reshape(4,4)
print(P)
print("\n")
print(P.T)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]


[[ 0  4  8 12]
 [ 1  5  9 13]
 [ 2  6 10 14]
 [ 3  7 11 15]]


**Output the array element indexes such that the array elements appear in the ascending
order**

In [46]:
q = np.random.choice(50,16,replace=False)
print(q)
print("\n")
print(np.sort(q))

[ 1 14  0 27  7 18 29 25 49 35  6 42 36 38 30 11]


[ 0  1  6  7 11 14 18 25 27 29 30 35 36 38 42 49]
